if ( GetLocale() ~= "ruRU" ) then
    _G.EzChatBar.lang = {}
    _G.EzChatBar.lang.name_button_size = "Button Size"
    _G.EzChatBar.lang.desc_button_size = "Set the button size from 1 to 100"
    _G.EzChatBar.lang.name_button_interval = "Button Interval"
    _G.EzChatBar.lang.desc_button_interval = "Set the interval between buttons from 1 to 20"
    _G.EzChatBar.lang.name_button_shape = "Button Shape"
    _G.EzChatBar.lang.desc_button_shape = "Select the shape of the bubbles"
    _G.EzChatBar.lang.name_button_orientation = "Orientation"
    _G.EzChatBar.lang.desc_button_orientation = "Select horizontal or vertical orientation"
    _G.EzChatBar.lang.name_bubbles_group = "Bubble Settings"
    _G.EzChatBar.lang.name_add_bubble = "Add Bubble"
    _G.EzChatBar.lang.desc_add_bubble = "Add a new bubble with default settings"
    _G.EzChatBar.lang.name_bubbles_tag = "Bubble "
    _G.EzChatBar.lang.name_cmd = "Command"
    _G.EzChatBar.lang.desc_cmd = "Enter the command for the bubble"
    _G.EzChatBar.lang.name_perm = "Visibility"
    _G.EzChatBar.lang.desc_perm = "When to display"
    _G.EzChatBar.lang.name_color = "Color"
    _G.EzChatBar.lang.desc_color = "Select the color of the bubble"
    _G.EzChatBar.lang.name_delete = "Delete Bubble"
    _G.EzChatBar.lang.desc_delete = "Delete this bubble"
    _G.EzChatBar.lang.name_reset_pos = "Reset position"
    _G.EzChatBar.lang.desc_reset_pos = "Reset position addon"

end