if ( GetLocale() ~= "ruRU" ) then

EZCHATBAR_CHATBARCOLOR_TITLE_EMOTE = "Guild"
EZCHATBAR_CHATBARCOLOR_TITLE_INSTANCE_CHAT = "Instance"
EZCHATBAR_CHATBARCOLOR_TITLE_OFFICER = "Officer"
EZCHATBAR_CHATBARCOLOR_TITLE_PARTY = "Party"
EZCHATBAR_CHATBARCOLOR_TITLE_RAID = "Raid"
EZCHATBAR_CHATBARCOLOR_TITLE_RAID_WARNING = "Raid warning"
EZCHATBAR_CHATBARCOLOR_TITLE_SAY = "Say"
EZCHATBAR_CHATBARCOLOR_TITLE_YELL = "Yell"
EZCHATBAR_GENERALTAB_BUTTON_CLOSE = "Close all"
EZCHATBAR_GENERALTAB_BUTTON_COMBATLOG = "Combat Log"
EZCHATBAR_GENERALTAB_BUTTON_DYGCLOSEALLTAB = "Close all tabs?"
EZCHATBAR_GENERALTAB_BUTTON_GENERAL = "General"
EZCHATBAR_GENERALTAB_BUTTON_NO = "No"
EZCHATBAR_GENERALTAB_BUTTON_SETTINGS = "Settings"
EZCHATBAR_GENERALTAB_BUTTON_YES = "Yes"
EZCHATBAR_SETTINGS1_CHECKBOX1 = "Standard panel Blizzard"
EZCHATBAR_SETTINGS1_CHECKBOX1_TITLE = "Enable the standard panel Blizzard"
EZCHATBAR_SETTINGS1_CHECKBOX2 = "Addon bar"
EZCHATBAR_SETTINGS1_CHECKBOX2_TITLE = "Show the addon bar"
EZCHATBAR_SETTINGS1_CHECKBOX3 = "The sound of an incoming message"
EZCHATBAR_SETTINGS1_CHECKBOX3_TITLE = "Notification of an incoming personal message"
--[[Translation missing --]]
--[[ EZCHATBAR_SETTINGS1_CHECKBOX4 = "Фиксация окна аддона"--]]
--[[Translation missing --]]
--[[ EZCHATBAR_SETTINGS1_CHECKBOX4_TITLE = "Блокирует перетаскивание окна аддона"--]]
EZCHATBAR_SETTINGS1_COLOR1 = "Background color"
EZCHATBAR_SETTINGS1_COLOR1_TITLE = "Notification of an incoming personal message"
EZCHATBAR_SETTINGS1_PANELNAME1 = "Dialog list settings"
EZCHATBAR_SETTINGS1_PANELNAME2 = "Chat history settings (In the development)"
EZCHATBAR_SETTINGS2_CHECKBOX1 = "Logging of chat (In the development)"
EZCHATBAR_SETTINGS2_CHECKBOX1_TITLE = "To include the preservation of the history of personal correspondence"

end